In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('./data/WBCD.csv')

In [3]:
df.head()

id  clump_thickness  uniformity_cell_size  uniformity_cell_shape  \
0  1000025                5                     1                      1   
1  1002945                5                     4                      4   
2  1015425                3                     1                      1   
3  1016277                6                     8                      8   
4  1017023                4                     1                      1   

   marginal_adhesion  single_epi_cell_size bare_nuclei  bland_chromatin  \
0                  1                     2           1                3   
1                  5                     7          10                3   
2                  1                     2           2                3   
3                  1                     3           4                3   
4                  3                     2           1                3   

   normal_nucleoli  mitosis  class  
0                1        1      2  
1                2        1      2  
2                1        1      2  
3                7        1      2  
4                1        1      2

In [4]:
import matlab.engine

In [5]:
eng = matlab.engine.start_matlab()

In [6]:
data = df.values
count =0
row = []
for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        if data[i][j] == '?':
            count+=1
            row.append(i)
            
print(count)
print(row)

16
[23, 40, 139, 145, 158, 164, 235, 249, 275, 292, 294, 297, 315, 321, 411, 617]


In [7]:
df = df.drop(row)

In [8]:
df.shape

(683, 11)

In [9]:
X = df.values

In [10]:
X.shape

(683, 11)

In [11]:
X

array([[1000025, 5, 1, ..., 1, 1, 2],
       [1002945, 5, 4, ..., 2, 1, 2],
       [1015425, 3, 1, ..., 1, 1, 2],
       ...,
       [888820, 5, 10, ..., 10, 2, 4],
       [897471, 4, 8, ..., 6, 1, 4],
       [897471, 4, 8, ..., 4, 1, 4]], dtype=object)

In [12]:
y = X[:,-1]
X = X[:,1:-1]

In [13]:
X.shape, y.shape

((683, 9), (683,))

In [14]:
X[45]

array([1, 1, 1, 1, 2, '1', 2, 1, 1], dtype=object)

In [15]:
for i in range(X.shape[0]):
    X[i][5] = int(X[i][5])


In [16]:
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        X[i][j] = float(X[i][j])

In [17]:
pred = []
for i in range(X.shape[0]):
    val = eng.evalFuzzy(X[i][0],X[i][1],X[i][2],X[i][3],X[i][4],X[i][5],X[i][6],X[i][7],X[i][8])
    pred.append(val)

In [18]:
pred = np.asarray(pred)

In [19]:
pred.shape

(683,)

In [20]:
pred

array([0.50050341, 0.83843391, 0.78798217, 0.83843391, 0.50050341,
       0.83822562, 0.5       , 0.50054404, 0.50050212, 0.50050341,
       0.50050341, 0.50050341, 0.82309017, 0.5       , 0.83843391,
       0.83843391, 0.50050341, 0.50050341, 0.83843391, 0.50050341,
       0.82407543, 0.83843391, 0.50050341, 0.50050341, 0.82309017,
       0.50050341, 0.50050341, 0.50050341, 0.50054555, 0.50050341,
       0.50050341, 0.83843391, 0.50050341, 0.50054404, 0.50050341,
       0.83822562, 0.50050341, 0.83843391, 0.82309017, 0.82309017,
       0.83822562, 0.83843391, 0.83822562, 0.50050212, 0.83843391,
       0.50050341, 0.50050341, 0.83843391, 0.83843391, 0.82309017,
       0.82788808, 0.83843391, 0.83843391, 0.83843391, 0.83822562,
       0.83843391, 0.82309017, 0.83843391, 0.82788808, 0.50057699,
       0.83822562, 0.82788808, 0.50050341, 0.82407543, 0.50050341,
       0.82788808, 0.82788808, 0.50050341, 0.50054555, 0.82407543,
       0.69988852, 0.83843391, 0.83843391, 0.65795406, 0.50050

In [21]:
def accuracy(pred, y ,split):
    y_calc = []
    right = 0
    wrong = 0
    for i in range(pred.shape[0]):
        if pred[i] < split:
            y_calc.append(2)
        else:
            y_calc.append(4)
    
    y_calc = np.array(y_calc)
    
    for i in range(y_calc.shape[0]):
        if y_calc[i] == y[i]:
            right+=1
        else:
            wrong+=1
            
    return right/y.shape[0]
    

In [22]:
split_arr = (np.arange(50)+50)/100

In [23]:
split_arr

array([0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ,
       0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71,
       0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 , 0.81, 0.82,
       0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 , 0.91, 0.92, 0.93,
       0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [24]:
acc = []
for i in split_arr:
    acc.append(accuracy(pred,y,i))

In [25]:
#acc

In [26]:
acc = np.asarray(acc)

In [27]:
np.argmax(acc)

30

In [28]:
acc

array([0.34992679, 0.91068814, 0.91947291, 0.91947291, 0.91947291,
       0.91947291, 0.91947291, 0.91947291, 0.91947291, 0.91947291,
       0.91947291, 0.91947291, 0.91947291, 0.91947291, 0.91947291,
       0.91947291, 0.9238653 , 0.9238653 , 0.9238653 , 0.92532943,
       0.93118594, 0.93557833, 0.93557833, 0.93850659, 0.93850659,
       0.94143485, 0.94143485, 0.94582723, 0.95754026, 0.97071742,
       0.97218155, 0.97218155, 0.97218155, 0.91215227, 0.65007321,
       0.65007321, 0.65007321, 0.65007321, 0.65007321, 0.65007321,
       0.65007321, 0.65007321, 0.65007321, 0.65007321, 0.65007321,
       0.65007321, 0.65007321, 0.65007321, 0.65007321, 0.65007321])

In [29]:
split_arr[np.argmax(acc)]

0.8

In [30]:
accuracy(pred,y,0.8)

0.972181551976574

In [31]:
for i in range(pred.shape[0]):
    if pred[i] < 0.8:
        pred[i] = 2
    else:
        pred[i] = 4

# Confusion Matrix


In [32]:
tp=0
tn=0
fp=0
fn=0

In [33]:
p=[]
for i in range(len(pred)):
    if y[i] ==2 and pred[i]==2:
        tn+=1
    if y[i] ==4 and pred[i]==4:
        tp+=1
    if y[i] ==2 and pred[i]==4:
        fp+=1
    if y[i] ==4 and pred[i]==2:
        fn+=1

In [34]:
print(tn,fp)
print(fn,tp)

426 18
1 238


In [35]:
precision=tp/(tp+fp)

In [36]:
precision

0.9296875

In [37]:
recall=tp/(tp+fn)

In [38]:
recall

0.99581589958159

In [39]:
tp+tn+fp+fn

683

In [40]:
f1=2*precision*recall/(precision+recall)

In [41]:
f1

0.9616161616161617